namespace MultiType.NET.Generators.Constants;

internal static class Consts
{
    public const string GeneratedCodeHeader = """
                                               //------------------------------------------------------------------------------
                                               // <auto-generated>
                                               //     This code was generated by MultiType.NET.SourceGenerator
                                               //     Library Version: {LibraryVersion}
                                               //     Runtime Version: {RuntimeVersion}
                                               //     Generated: {GenerationTime}
                                               //
                                               //     Changes to this file may cause incorrect behavior and will be lost if
                                               //     the code is regenerated.
                                               // </auto-generated>
                                               //------------------------------------------------------------------------------

                                               """;

    public const string AnyTypeGeneratedFileSuffix = "_Generated.g.cs";
    public const string AnysCoreNamespace = "global::MultiType.NET.Core.Anys.Generated";
    public const string DiagnosticCategory = "MultiType.NET";
    public const string AttributeNamespace = "MultiType.NET.Core.Attributes";
    public const string AttributeName = "GenerateAnyAttribute";
}