namespace MultiType.NET.SourceGenerator;

using System;
using System.IO;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

internal static class UnionEmitter
{
    private const string GeneratedCodeHeader = """
                                               //------------------------------------------------------------------------------
                                               // <auto-generated>
                                               //     This code was generated by MultiType.NET.SourceGenerator
                                               //     Library Version: {LibraryVersion}
                                               //     Runtime Version: {RuntimeVersion}
                                               //     Generated: {GenerationTime}
                                               //
                                               //     Changes to this file may cause incorrect behavior and will be lost if
                                               //     the code is regenerated.
                                               // </auto-generated>
                                               //------------------------------------------------------------------------------

                                               """;
    public const string UnionNamespace = "MultiType.NET.Core.Unions.Generated";
    public const string UnionJsonConverterNamespace = "MultiType.NET.Core.Serialization.Generated";
    private static readonly string OutputPath = Path.Combine(
        AppDomain.CurrentDomain.BaseDirectory,
        "..", // go up to bin
        "..", // go up to Debug/Release
        "..", // go up to project root
        "..", // go up to solution
        "MultiType.NET.Core",
        "Unions",
        "Generated"
    );
    
    private static readonly string OutputSerializationPath = Path.Combine(
        AppDomain.CurrentDomain.BaseDirectory,
        "..", // go up to bin
        "..", // go up to Debug/Release
        "..", // go up to project root
        "..", // go up to solution
        "MultiType.NET.Core",
        "UnionSerializations",
        "Generated"
    );
    private const int MinArity = 2;

    public static void EmitUnionTypes(int maxArity = 16)
    {
        Directory.CreateDirectory(OutputPath);
        Directory.CreateDirectory(OutputSerializationPath);
        
        for (int arity = MinArity; arity <= maxArity; arity++)
        {
            Console.WriteLine($"Generating union type for arity {arity}...");
            var content = new UnionTypeBuilder(arity, UnionNamespace)
                .AddCoreStructure()
                // equality
                .AddEqualityMembers()
                // match
                .AddMatchMethods()
                .AddTryMatchMethods()
                // get
                .AddGetMethods()
                .AddTryGetMethods()
                // map
                .AddMapMethods()
                // select
                .AddSelectMethods()
                // switch
                .AddSwitchMethods()
                // de-construct
                .AddDeconstructMethod()
                .Build();
            
            var formattedContent = FormattedContent(content);


            Console.WriteLine($"Writing union type for arity {arity}...");
            File.WriteAllText(
                Path.Combine(OutputPath, $"Union{arity}.g.cs"), 
                formattedContent);
            
            Console.WriteLine($"'Union{arity}.g.cs' Generated");
        }

        for (int arity = MinArity; arity <= maxArity; arity++)
        {
            Console.WriteLine($"Generating union type json serialization converter for arity {arity}...");
            var content = new UnionJsonConverterBuilder(arity, UnionNamespace, UnionJsonConverterNamespace)
                .AddHeaders()
                .AddReadMethod()
                .AddWriteMethod()
                .Build();
            
            var formattedContent = FormattedContent(content);
            
            Console.WriteLine($"Writing union type json converter for arity {arity}...");
            File.WriteAllText(
                Path.Combine(OutputSerializationPath , $"Union{arity}JsonConverter.g.cs"), 
                formattedContent);
            
            Console.WriteLine($"'Union{arity}JsonConverter.g.cs' Generated");
        }
    }

    private static string FormattedContent(string? content)
    {
        // Add nullable enable directive and format the code
        var formattedContent = FormatCode($$"""
                                            {{GetGeneratedCodeHeader()}}

                                            #nullable enable

                                            {{content}}
                                            """);
        return formattedContent;
    }

    private static string FormatCode(string sourceCode)
    {
        var tree = CSharpSyntaxTree.ParseText(sourceCode);
        var root = tree.GetRoot();
        var formatted = root.NormalizeWhitespace();
        return formatted.ToFullString();
    }

    private static string GetGeneratedCodeHeader()
    {
        var runtimeVersion = Environment.Version.ToString();
        var generationTime = DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm:ss");
        var libraryVersion = typeof(UnionEmitter).Assembly.GetName().Version?.ToString() ?? "0.0.0";

        return GeneratedCodeHeader
            .Replace("{LibraryVersion}", libraryVersion)
            .Replace("{RuntimeVersion}", runtimeVersion)
            .Replace("{GenerationTime}", generationTime + " UTC");
    }

}
